modLoader="javafml"
loaderVersion="[4,)"

license="All rights reserved"

[[mods]]
modId="missingtrims"
version="1.0.0"
displayName="Your Mod Name"
description='''Your mod description here.'''

[[dependencies.missingtrims]]
modId="neoforge"
type="required"
versionRange="[21.0.0,)"

[[dependencies.missingtrims]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
